apiVersion: apps/v1
kind: Deployment
metadata:
  name: monolith
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: monolith
  template:
    metadata:
      labels:
        app: monolith
    spec:
      containers:
      - image: gcr.io/eventstorming-tool/monolith:v0.1
        name: monolith
        ports:
        - containerPort: 8080
