--- 
apiVersion: "apps/v1"
kind: "Deployment"
metadata: 
  name: "nginx"
  labels: 
    app: "nginx"
  annotations: 
    msaez.io/x: "749"
    msaez.io/y: "363"
spec: 
  selector: 
    matchLabels: 
      app: "nginx"
  replicas: 1
  template: 
    metadata: 
      labels: 
        app: "nginx"
    spec: 
      containers: 
        - 
          name: "nginx"
          image: "nginx"
          ports: 
            - 
              containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monolith
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: monolith
  template:
    metadata:
      labels:
        app: monolith
    spec:
      containers:
      - image: sanghoon01/monolith:d64166c
        name: monolith
        ports:
        - containerPort: 8080